spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/payflow
    username: payflow
    password: payflow
  flyway:
    enabled: true
    locations: classpath:db/migration
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}

payflow:
  security:
    encryption-key: ${ENCRYPTION_KEY:M+Gn9EGNdnD8i/r1+Pu9ipAZfBjsfahlPsyVvgbqT80=}
    jwt:
      secret: ${JWT_SECRET:DwYOwf5/PG/Mpk6zODEfFznfCeCjKLbCmVGBZG0n3FrE0YGvFrUVd7Pb2A0ZGBrP}
  provider:
    mock:
      base-url: ${MOCK_PROVIDER_BASE_URL:http://localhost:8081}
      webhook-secret: ${MOCK_PROVIDER_WEBHOOK_SECRET:dev-mock-webhook-secret-3f8a91c2}

logging:
  level:
    com.payflow: DEBUG
