spring:
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
  flyway:
    enabled: true
    locations: classpath:db/migration
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}

payflow:
  security:
    encryption-key: ${ENCRYPTION_KEY}
    jwt:
      secret: ${JWT_SECRET}
  provider:
    mock:
      base-url: ${MOCK_PROVIDER_BASE_URL}

management:
  endpoint:
    health:
      show-details: never

logging:
  level:
    com.payflow: INFO
