spring:
  flyway:
    enabled: true
    locations: classpath:db/migration

payflow:
  security:
    encryption-key: M+Gn9EGNdnD8i/r1+Pu9ipAZfBjsfahlPsyVvgbqT80=
    jwt:
      secret: DwYOwf5/PG/Mpk6zODEfFznfCeCjKLbCmVGBZG0n3FrE0YGvFrUVd7Pb2A0ZGBrP

logging:
  level:
    com.payflow: DEBUG
    org.testcontainers: INFO
